### ISSUE TITLE
OnRequestClose prop is not supplied.

### ISSUE THREAD

**Issue by ngsison** [netyouli/react-native-whc-loading#1]
![image](https://user-images.githubusercontent.com/20357514/41099067-fdf6e55a-6a8f-11e8-9d58-fff2a65e7d44.png)

**Comment by yuwenbai** [comment]
author must be iphone user 
just add onRequestClose={() => {} to the index file

**Comment by ngsison** [comment]
I already created a Pull Request for it. But author as no response yet.

**Comment by aikhan** [comment]
Same problem 
Author is sleeping
